### ISSUE TITLE
checkWimpsProfitable is always false

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/WurzelimperiumBot#53]
I have tested the function `checkWimpsProfitable` with all of my accounts. And all wimps were declined.
My assumption is that selling to a wimp is only profitable if the products were grown in the own garden and not bought in the shops.

See commit https://github.com/MasterZydra/WurzelimperiumBot/commit/1d8defb054325d14c157118a29247aa421746421

**Comment by Cl0ckm4n** [comment]
Yeah, thats because the wimp base-prices are calculated based on the shop prices times a factor between 0 to 1.

Maybe it would be useful to implement the profitability-check in a way you can set the maximum loss to e.g. 10% compared to the shopprices?! This way you wouldn't make too much loss and get the points from the wimp sales.

**Comment by MasterZydra** [comment]
Thanks for the details. I did not know that.
I guess that would be a good approach.
