### ISSUE TITLE
development plans?!

### ISSUE THREAD

**Issue by Cl0ckm4n** [MasterZydra/WurzelimperiumBot#66]
I'm just curious.
Are any features planned or already being worked on by you guys?
Does the bot cover all your needs?
Or do you maybe have feature suggestions/requests?

For me the bot lacks the automation of the bees. So i started to refactor the code for bees and automate the bee sending and after that i want to add custom changing the hiveType (independent from Quests).

Would love to hear your thoughts :D

**Comment by Cl0ckm4n** [comment]
Ok nice to hear that you have something in mind.

to 1: so you don't want to change the plant in the python script itself, right? Maybe a webGUI would be better for this interactions than the notes tab (but probably more work...).
to 2: for example automatically throwing the snowballs like it was in the last event?
to 3: i implemented this for the "Bonusgegenstände", but only with the Premium-Button to collect all at once; Erholungsgarten is a nice idea and shouldn't be too hard
to 4: yeah definitely and recently bulgarian got added too. For me it is more important that as many features are working as possible ^^

to bees: i do it half-automated. i let plant the products and then set the hives according to the plants... You would want it to be fully automated that the hives always match the plants in the gardens?

**Comment by MasterZydra** [comment]
- Regarding 1:  
  There is already a setting via the notes: [Feature: set the minimum stock](https://app.pluralsight.com/library/courses/kubernetes-getting-started-2023/table-of-contents)
  This has the advantage that I can configure it in wurzelimperium itself. And can change it depending on the demands for e.g. the current quests, ...
- Regarding 2:
  The snowball games could be a bit complicated because it is JavaScript. But e.g. the advent calendar or the halloween games should be possible.
- Regarding 4: "*For me it is more important that as many features are working as possible*"
  My issue is that adding new features gets more complicated each time. My idea is e.g. to have a HTTPConnection class that does not contain all the requests. They could be in the e.g. Garden, Bonsai, etc. class itself or in a HttpGarden, ... class. If it is splitted in more smaller modules, I think it would be easier to change or add something without all that merge conflicts because the code is placed in separate files. And the Wurzelbot class should contains as little logic as possible. The logic could be placed in another class.
- Regarding bees:
  It does not have to be fully automated. I think with the feature that I can configure that e.g. only strawberries should be planted and the automation for harvesting, it would be good enough for me.

**Comment by Cl0ckm4n** [comment]
1: oh i didn't know that... i'll look into it
2: lets wait for the events and see what is possible ^^
4: maybe use the HTTP-class as parent class and then create a own HTTP-child-class for each feature

**Comment by MasterZydra** [comment]
Hi @Cl0ckm4n,

I made an example of how the refactured code could look like: https://github.com/MasterZydra/WurzelimperiumBot/commit/de7aa280b9392b229ad54c82ff0a1ef7e54c8bfd
What do you think?
This way the code is encapsulated in each module, in this case a `note` and `core` module.

**Comment by Cl0ckm4n** [comment]
I think the singleton variant looks very promising.

You would then create a folder with the Http.py and Feature.py for each feature?
If i understand it right, the core module would contain all modules that are used in more submodules, e.g. Spieler.py or Lager.py?

It makes sense then to put the logic for processing the http response and content inside of each http.py submodule.

**Comment by Cl0ckm4n** [comment]
In my opinion this sounds fine. I think it becomes clear during programming what is good and where there is room for improvement.
I have to finish the features i have begun to code then i can try to start restructuring the code too.

I like the concept to encapsulate manual and fully automation of features to prevent circular dependencies.

**Comment by MasterZydra** [comment]
Moved ideas into one issue #84
