### ISSUE TITLE
Coding standard

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/WurzelimperiumBot#74]
Hello everyone,

As every contributor has their own coding style and with a lot of commits, existing and working code gets changed to another coding style, I thought a common standard for this project would help.

That way, we can focus on new features instead of changing "good enough code" just to fit your own coding style.

My ideas for the coding style / contribution rules:
1. **Prioritize readability over cleverness**:  
    This article is more or less the way I think about it:  
    https://remarkablemark.org/blog/2022/01/16/readable-versus-clever-code/
2. **Keep changes small**:
    Refactoring is great and absolutely necessary! However, if a new feature is added and the same commit includes numerous small changes such as indentation and empty lines, it can be challenging to perform a code review.
3. **Coding in English**:
    Because the WurzelimperiumBot is now also used for e.g. the Bugarian Wurzelimperium equivalent, it would be more accessible for new contributors if the code is written in English.
4. **Python Coding Standard Recommendations**
   There is a coding standard on the official python website. We should try to follow it:
    https://peps.python.org/pep-0008/#function-and-variable-names

What do you think? Do you have more rules that should be added?

@xRuffKez, @Cl0ckm4n , @Pazze12, @Fauster, @MrFlamez

**Comment by Fauster** [comment]
I completely agree with the "English only" rule.

As a translator, I have some knowledge of both German and English, which is why I had to use Bulgarian comments in the code.

My honest opinion is that even the code within different tasks is scattered. However, that's a separate issue as relatively few people participate.

Touching the article:

It's essential for a community working on a project to have readable code. While we have different styles, that doesn't change the fact that we're all working towards the same goal.
While it's understandable that some of us may not understand different languages, please don't hesitate to ask a translator for help. My participation aimed to help uncover the *secrets* of the German language and Bulgarian language.  Still, I can also help with English.

Cheers! 
P.S. Very well thought. 
:smiley:

**Comment by Cl0ckm4n** [comment]
I totally agree to your points.
I would also suggest to align the naming of functions and variables.
At the moment the readability is not optimal, thus i would  prefer using the snake-case sytle: [https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/).

**Comment by MasterZydra** [comment]
> I totally agree to your points. I would also suggest to align the naming of functions and variables. At the moment the readability is not optimal, thus i would prefer using the snake-case sytle: https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/.

Personally my preference would be Camel Case. But the recommendation on the official python website says snake case:
https://peps.python.org/pep-0008/#function-and-variable-names

So my suggestion would be following the "official" python standard.
